[package]
name = "sensors"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "pir-sensor"
path = "src/pir.rs"

[[bin]]
name = "button-test"
path = "src/bin/button_test.rs"

[[bin]]
name = "mpu6050-sensor"
path = "src/mpu6050.rs"

[dependencies]
gpio_core = { path = "../gpio_core" }
tokio.workspace = true
anyhow.workspace = true
rppal.workspace = true
