gpio:
  led:
    pir_led_pin: 26
  button:
    lighting_override_pin: 21
    lighting_brightness_pin: 20
  pir:
    pin: 16

lcd:
  i2c_address: 0x27

mpu6050:
  i2c_bus: 1

system:
  presence_timeout_secs: 120
  default_brightness: 100
