gpio:
  led:
    pir_led_pin: 26
  rgb_led:
    system:
      red_pin: 23
      green_pin: 24
      blue_pin: 25
  button:
    lighting_override_pin: 21
    lighting_brightness_pin: 20
  pir:
    pin: 16

lcd:
  i2c_address: 0x27

system:
  presence_timeout_secs: 120
  default_brightness: 100
  brightness_levels: [25, 50, 75, 100]
